#pragma once

#include <stdint.h>

enum OrgeScancode {
	ORGE_SCANCODE_A = 0,
	ORGE_SCANCODE_B,
	ORGE_SCANCODE_C,
	ORGE_SCANCODE_D,
	ORGE_SCANCODE_E,
	ORGE_SCANCODE_F,
	ORGE_SCANCODE_G,
	ORGE_SCANCODE_H,
	ORGE_SCANCODE_I,
	ORGE_SCANCODE_J,
	ORGE_SCANCODE_K,
	ORGE_SCANCODE_L,
	ORGE_SCANCODE_M,
	ORGE_SCANCODE_N,
	ORGE_SCANCODE_O,
	ORGE_SCANCODE_P,
	ORGE_SCANCODE_Q,
	ORGE_SCANCODE_R,
	ORGE_SCANCODE_S,
	ORGE_SCANCODE_T,
	ORGE_SCANCODE_U,
	ORGE_SCANCODE_V,
	ORGE_SCANCODE_W,
	ORGE_SCANCODE_X,
	ORGE_SCANCODE_Y,
	ORGE_SCANCODE_Z,
	ORGE_SCANCODE_1,
	ORGE_SCANCODE_2,
	ORGE_SCANCODE_3,
	ORGE_SCANCODE_4,
	ORGE_SCANCODE_5,
	ORGE_SCANCODE_6,
	ORGE_SCANCODE_7,
	ORGE_SCANCODE_8,
	ORGE_SCANCODE_9,
	ORGE_SCANCODE_0,
	ORGE_SCANCODE_RETURN,
	ORGE_SCANCODE_ESCAPE,
	ORGE_SCANCODE_BACKSPACE,
	ORGE_SCANCODE_TAB,
	ORGE_SCANCODE_SPACE,
	ORGE_SCANCODE_MINUS,
	ORGE_SCANCODE_EQUALS,
	ORGE_SCANCODE_LEFTBRACKET,
	ORGE_SCANCODE_RIGHTBRACKET,
	ORGE_SCANCODE_BACKSLASH,
	ORGE_SCANCODE_NONUSHASH,
	ORGE_SCANCODE_SEMICOLON,
	ORGE_SCANCODE_APOSTROPHE,
	ORGE_SCANCODE_GRAVE,
	ORGE_SCANCODE_COMMA,
	ORGE_SCANCODE_PERIOD,
	ORGE_SCANCODE_SLASH,
	ORGE_SCANCODE_RIGHT,
	ORGE_SCANCODE_LEFT,
	ORGE_SCANCODE_DOWN,
	ORGE_SCANCODE_UP,
};

enum OrgeMouseButton {
	ORGE_MOUSE_BUTTON_LEFT = 0,
	ORGE_MOUSE_BUTTON_MIDDLE,
	ORGE_MOUSE_BUTTON_RIGHT,
};

struct OrgeGetKeyStateParam {
	OrgeScancode scancode;
	int32_t *out;
};

struct OrgeGetCursorParam {
	uint32_t *outX;
	uint32_t *outY;
};

struct OrgeGetMouseButtonStateParam {
	OrgeMouseButton button;
	int32_t *out;
};
