#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "audio.h"
#include "compute.h"
#include "dialog.h"
#include "input.h"
#include "rendering.h"
#include "resource.h"
#include "text.h"
#include "window.h"

enum OrgeApiCallType {
	ORGE_SHOW_DIALOG = 0,
	ORGE_SHOW_ERROR_DIALOG,

	ORGE_INITIALIZE,
	ORGE_TERMINATE,
	ORGE_UPDATE,

	ORGE_IS_FULLSCREEN,
	ORGE_SET_FULLSCREEN,

	ORGE_CREATE_BUFFER,
	ORGE_DESTROY_BUFFER,
	ORGE_UPDATE_BUFFER,
	ORGE_COPY_BUFFER_TO,
	ORGE_UPDATE_BUFFER_DESCRIPTOR,
	ORGE_UPDATE_COMPUTE_BUFFER_DESCRIPTOR,
	ORGE_LOAD_IMAGE,
	ORGE_DESTROY_IMAGE,
	ORGE_CREATE_STORAGE_IMAGE,
	ORGE_DESTROY_STORAGE_IMAGE,
	ORGE_UPDATE_IMAGE_DESCRIPTOR,
	ORGE_UPDATE_COMPUTE_IMAGE_DESCRIPTOR,
	ORGE_UPDATE_COMPUTE_STORAGE_IMAGE_DESCRIPTOR,
	ORGE_CREATE_SAMPLER,
	ORGE_DESTROY_SAMPLER,
	ORGE_UPDATE_SAMPLER_DESCRIPTOR,
	ORGE_UPDATE_COMPUTE_SAMPLER_DESCRIPTOR,
	ORGE_UPDATE_INPUT_ATTACHMENT_DESCRIPTOR,
	ORGE_LOAD_MESH,
	ORGE_DESTROY_MESH,

	ORGE_RASTERIZE_CHARACTERS,
	ORGE_LAYOUT_TEXT,
	ORGE_DRAW_TEXTS,

	ORGE_BEGIN_RENDER,
	ORGE_END_RENDER,
	ORGE_BIND_MESH,
	ORGE_BEGIN_RENDER_PASS,
	ORGE_END_RENDER_PASS,
	ORGE_NEXT_SUBPASS,
	ORGE_BIND_PIPELINE,
	ORGE_DRAW,
	ORGE_DRAW_DIRECTLY,

	ORGE_BIND_COMPUTE_PIPELINE,
	ORGE_DISPATCH,

	ORGE_GET_KEY_STATE,
	ORGE_GET_CURSOR,
	ORGE_GET_MOUSE_BUTTON_STATE,

	ORGE_GET_AUDIO_CHANNEL_VOLUME,
	ORGE_SET_AUDIO_CHANNEL_VOLUME,
	ORGE_LOAD_WAVE,
	ORGE_DESTROY_WAVE,
	ORGE_PLAY_WAVE,
};

enum OrgeApiResult {
	ORGE_OK = 0,
	ORGE_ERROR,
	ORGE_WINDOW_CLOSED,
	ORGE_AUDIO_CHANNEL_NOT_INITIALIZED,
};

#ifdef _WIN32
# ifdef ORGE_BUILD_SHARED
#  __declspec(dllexport)
# elif ORGE_USE_SHARED
#  __declspec(dllimport)
# endif
#endif
OrgeApiResult orgeApiCall(OrgeApiCallType type, void *param);

#ifdef __cplusplus
}
#endif
