title: input
width: 640
height: 480
attachments:
  - id: RT
    format: render-target
    clear-value: [0.0, 0.0, 0.0, 1.0]
subpasses:
  - id: SP
    outputs: [RT]
pipelines:
  - id: PL
    vertex-shader: shader.vert.spv
    fragment-shader: shader.frag.spv
    desc-sets:
      - count: 3
        bindings:
          - type: uniform-buffer
            stage: fragment
    vertex-input-attributes: [3]
    color-blends: [false]
    subpass: SP
