title: multipass
width: 640
height: 480
assets:
  - colored-triangle.mesh.v
  - colored-triangle.mesh.i
  - square.mesh.v
  - square.mesh.i
  - mesh.vert.spv
  - mesh.frag.spv
  - pattern.vert.spv
  - pattern.frag.spv
  - integration.vert.spv
  - integration.frag.spv
meshes:
  - id: triangle
    vertices: colored-triangle.mesh.v
    indices: colored-triangle.mesh.i
  - id: square
    vertices: square.mesh.v
    indices: square.mesh.i
attachments:
  - id: mesh-rt
    format: share-color-attachment
    clear-value: [0.0, 0.0, 0.0, 1.0]
  - id: pattern-rt
    format: signed-share-color-attachment
    clear-value: [0.0, 0.0, 0.0, 0.0]
  - id: RT
    format: render-target
    clear-value: [0.0, 0.0, 0.0, 1.0]
pipelines:
  - id: mesh-pl
    vertex-shader: mesh.vert.spv
    fragment-shader: mesh.frag.spv
    vertex-input-attributes: [3, 4]
    color-blends: [false]
  - id: pattern-pl
    vertex-shader: pattern.vert.spv
    fragment-shader: pattern.frag.spv
    desc-sets:
      - count: 1
        bindings:
          - type: uniform-buffer
            stage: vertex
    vertex-input-attributes: [3, 2]
    color-blends: [false]
  - id: integration-pl
    vertex-shader: integration.vert.spv
    fragment-shader: integration.frag.spv
    desc-sets:
      - count: 1
        bindings:
          - type: texture
            stage: fragment
          - type: input-attachment
            stage: fragment
          - type: sampler
            stage: fragment
    vertex-input-attributes: [3, 2]
    color-blends: [false]
render-passes:
  - id: RP
    subpasses:
      - id: mesh-sp
        outputs: [mesh-rt]
        pipelines: [mesh-pl]
      - id: pattern-sp
        outputs: [pattern-rt]
        pipelines: [pattern-pl]
      - id: integration-sp
        inputs: [mesh-rt, pattern-rt]
        outputs: [RT]
        depends: [mesh-sp, pattern-sp]
        pipelines: [integration-pl]
