title: triangle
width: 640
height: 480
attachments:
 - id: main-att
   format: render-target
   final-layout: present-src
   clear-value: [0.25, 0.25, 0.25, 1.0]
subpasses:
 - id: main-sp
   outputs:
    - id: main-att
      layout: color-attachment
