title: triangle in Rust
width: 640
height: 480
assets:
  - colored-triangle.mesh.v
  - colored-triangle.mesh.i
  - shader.vert.spv
  - shader.frag.spv
meshes:
  - id: triangle
    vertices: colored-triangle.mesh.v
    indices: colored-triangle.mesh.i
attachments:
  - id: RT
    format: render-target
    clear-value: [0.0, 0.0, 0.0, 1.0]
subpasses:
  - id: SP
    outputs: [RT]
pipelines:
  - id: PL
    vertex-shader: shader.vert.spv
    fragment-shader: shader.frag.spv
    vertex-input-attributes: [3, 4]
    color-blends: [false]
    subpass: SP
