name: Build on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          libx11-dev \
          libxcb1-dev \
          libxkbcommon-dev \
          libwayland-dev \
          libxrandr-dev \
          libltdl-dev \
          pkg-config

    - name: Cache vcpkg packages
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: |
          vcpkg_installed
          vcpkg/buildtrees
          vcpkg/packages
          vcpkg/vcpkg
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json', 'triplets/**', '.gitmodules') }}

    - name: Install packages
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      env:
        VCPKG_FORCE_SYSTEM_BINARIES: 1
        ACLOCAL_PATH: /usr/share/aclocal
      run: |
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install --triplet custom-x64-linux --overlay-triplets=./triplets

    - name: Build & install orge
      run: |
        cmake -G Ninja -B build -D ORGE_SHARED=ON -D ORGE_STATIC=ON -D BUID_EXAMPLES=ON -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/opt/orge
        cmake --build build
        cmake --install build

    - name: Upload orge artifacts
      uses: actions/upload-artifact@v4
      with:
        name: orge-lib
        path: |
          /opt/orge
          ./examples/simple/main.cpp

  test-standalone:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download orge artifacts
      uses: actions/download-artifact@v4
      with:
        name: orge-lib
        path: /

    - name: Prepare
      run: |
        mkdir shared
        mkdir static

    - name: Test build with shared
      working-directory: shared
      run: g++ ../examples/simple/main.cpp $(pkg-config orge --cflags --libs --with-path /opt/orge/lib/pkgconfig)

    - name: Test build with static
      working-directory: static
      run: g++ ../examples/simple/main.cpp $(pkg-config orgestatic --cflags --libs --static --with-path /opt/orge/lib/pkgconfig)
