name: Build on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install dependencies
      run: choco install pkgconfiglite

    - name: Cache vcpkg packages
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: |
          vcpkg_installed_shared
          vcpkg_installed_static
          vcpkg/buildtrees
          vcpkg/packages
          vcpkg/vcpkg.exe
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json', 'triplets/**', '.gitmodules') }}

    - name: Setup vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: vcpkg\bootstrap-vcpkg.bat

    - name: Build & install orge (shared)
      run: |
        cmake -G Ninja -B build -D ORGE_SHARED=ON -D ORGE_STATIC=OFF -D BUILD_EXAMPLES=ON -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=C:\orge
        cmake --build build
        cmake --install build

    - name: Build & install orge (static)
      run: |
        cmake -G Ninja -B build -D ORGE_SHARED=OFF -D ORGE_STATIC=ON -D BUILD_EXAMPLES=ON -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=C:\orge
        cmake --build build
        cmake --install build

    - name: Copy example file
      run: copy examples\simple\main.cpp C:\orge\

    - name: Upload orge artifacts
      uses: actions/upload-artifact@v4
      with:
        name: orge-lib
        path: C:\orge

  test-standalone:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies
      run: choco install pkgconfiglite

    - name: Download orge artifacts
      uses: actions/download-artifact@v4
      with:
        name: orge-lib
        path: C:\orge

    - name: Prepare
      run: |
        mkdir shared
        mkdir static

    - run: type C:\orge\lib\pkgconfig\orge.pc

    - name: Debug pkg-config output
      shell: pwsh
      env:
        PKG_CONFIG_PATH: C:\orge\lib\pkgconfig
      run: |
        pkg-config orge --cflags
        pkg-config orge --libs

    - name: Test build with shared
      working-directory: shared
      shell: pwsh
      env:
        PKG_CONFIG_PATH="C:\orge\lib\pkgconfig"
      run: |
        $cflags = pkg-config orge --cflags
        $libs = pkg-config orge --libs
        echo $cflags
        echo $(pkg-config orge --cflags)
        echo "$(pkg-config orge --cflags)"
        cl /IC:/orge/include /EHsc /std:c++20 /MD C:\orge\main.cpp /link /LIBPATH:C:/orge/lib orge.lib

    - name: Test build with static
      working-directory: static
      run: |
        cl /IC:/orge/include /EHsc /std:c++20 /MT C:\orge\main.cpp /link /LIBPATH:C:/orge/lib orgestatic.lib
