name: Build on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install dependencies
      run: choco install pkgconfiglite

    - name: install meson
      run: pip install meson

    - name: Cache vcpkg packages
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: |
          vcpkg_installed_static
          vcpkg_installed_shared
          vcpkg/buildtrees
          vcpkg/packages
          vcpkg/vcpkg.exe
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json', 'triplets/**', '.gitmodules') }}

    - name: Setup vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: |
        vcpkg\bootstrap-vcpkg.bat
        vcpkg\vcpkg install --overlay-triplets=.\triplets --triplet=custom-x64-windows-static --x-install-root=vcpkg_installed_static
        vcpkg\vcpkg install --overlay-triplets=.\triplets --triplet=custom-x64-windows-shared --x-install-root=vcpkg_installed_shared

    - name: Build & install orge (static)
      run: |
        dir ${{ github.workspace }}
        dir ${{ github.workspace }}\vcpkg_installed_static
        dir ${{ github.workspace }}\vcpkg_installed_static\custom-x64-windows-static
        dir ${{ github.workspace }}\vcpkg_installed_static\custom-x64-windows-static\lib
        dir ${{ github.workspace }}\vcpkg_installed_static\custom-x64-windows-static\lib\pkgconfig
        setx PKG_CONFIG_PATH=${{ github.workspace }}\vcpkg_installed_static\custom-x64-windows-static\lib\pkgconfig
        meson setup build-static -Dbuildtype=release --prefix=D:\orge\installed-static --native-file=.\meson\native-windows.ini
        meson install -C build-static

    - name: Build & install orge (shared)
      run: |
        setx PKG_CONFIG_PATH=${{ github.workspace }}\vcpkg_installed_shared\custom-x64-windows-shared\lib\pkgconfig
        meson setup build-shared -Dbuildtype=release -Ddefault_library=shared --prefix=D:\orge\installed-shared --native-file=.\meson\native-windows.ini
        meson install -C build-shared

    - name: Copy example file
      run: copy examples\simple\main.cpp D:\orge\

    - name: Upload orge artifacts
      uses: actions/upload-artifact@v4
      with:
        name: orge-lib
        path: D:\orge

  test-standalone:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies
      run: choco install pkgconfiglite

    - name: Download orge artifacts
      uses: actions/download-artifact@v4
      with:
        name: orge-lib
        path: D:\orge

    - name: Prepare
      run: |
        mkdir shared
        mkdir static

    - name: Test build with shared
      working-directory: shared
      shell: cmd
      env:
        PKG_CONFIG_PATH: D:\orge\lib\pkgconfig
      run: |
        for /f "delims=" %%i in ('pkg-config orge --cflags') do set CFLAGS=%%i
        for /f "delims=" %%j in ('pkg-config orge --libs') do set LIBS=%%j
        cl %CFLAGS% D:\orge\main.cpp /link %LIBS%

    - name: Test build with static
      working-directory: static
      shell: cmd
      env:
        PKG_CONFIG_PATH: D:\orge\lib\pkgconfig
      run: |
        for /f "delims=" %%i in ('pkg-config orgestatic --cflags') do set CFLAGS=%%i
        for /f "delims=" %%j in ('pkg-config orgestatic --libs --static') do set LIBS=%%j
        cl %CFLAGS% D:\orge\main.cpp /link %LIBS%
