name: Build on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          libx11-dev \
          libxcb1-dev \
          libxkbcommon-dev \
          libwayland-dev \
          libxrandr-dev \
          pkg-config

    - name: Cache thirdparty build
      id: cache-thirdparty
      uses: actions/cache@v3
      with:
        path: build/deps
        key: ${{ runner.os }}-thirdparty-${{ hashFiles('thirdparty/setup.sh', '.gitmodules') }}
        restore-keys: |
          ${{ runner.os }}-thirdparty-

    - name: Setup thirdparty libraries
      if: steps.cache-thirdparty.outputs.cache-hit != 'true'
      run: |
        cd thirdparty
        ./setup.sh

    - name: Build orge
      run: |
        cmake -G Ninja -S . -B build -D ORGE_SHARED=ON -D ORGE_STATIC=ON -D BUILD_EXAMPLES=ON -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/opt/orge
        cmake --build build

    - name: Install orge
      run: cmake --install build

    - name: Upload orge artifacts
      uses: actions/upload-artifact@v4
      with:
        name: orge-lib
        path: |
          /opt/orge
          ./examples/simple/main.cpp

  test-standalone:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download orge artifacts
      uses: actions/download-artifact@v4
      with:
        name: orge-lib

    - name: Prepare
      run: |
        mkdir shared
        mkdir static

    - name: Test build with shared
      working-directory: shared
      run: g++ ./examples/simple/main.cpp $(pkg-config orge --cflags --libs --with-path /opt/orge/lib/pkgconfig)

    - name: Test build with static
      working-directory: static
      run: g++ ./examples/simple/main.cpp $(pkg-config orgestatic --cflags --libs --static --with-path /opt/orge/lib/pkgconfig)
