title: text
width: 640
height: 480
attachments:
  - id: RT
    format: render-target
    clear-value: [0.0, 0.0, 0.0, 1.0]
subpasses:
  - id: SP
    outputs: [RT]
pipelines:
  - id: PL
    vertex-shader: shader.vert.spv
    fragment-shader: shader.frag.spv
    desc-sets:
      - count: 1
        bindings:
          - type: texture
            stage: fragment
          - type: sampler
            stage: fragment
    vertex-input-attributes: [3, 2]
    color-blends: [false]
    subpass: SP
char-size: 24
char-atlus-col: 12
char-atlus-row: 12
