title: text
width: 640
height: 480
assets:
  - MPLUS1p-Regular.ttf
fonts:
  - id: font
    file: MPLUS1p-Regular.ttf
    char-size: 28
    char-atlus-col: 7
    char-atlus-row: 7
attachments:
  - id: RT
    format: render-target
    clear-value: [0.0, 0.0, 0.0, 1.0]
render-passes:
  - id: RP
    subpasses:
      - id: SP
        outputs: [RT]
        pipelines: ["@text@"]
